// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC12Q8gbHWRgxncs-6pD24aQvW0a36Jro',
    appId: '1:501979216694:web:976f895cf19db558d41197',
    messagingSenderId: '501979216694',
    projectId: 'scholrx-beed0',
    authDomain: 'scholrx-beed0.firebaseapp.com',
    storageBucket: 'scholrx-beed0.firebasestorage.app',
    measurementId: 'G-60MD1V1XV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvW7KctJsLAfhpZmbbhvV89GkVzlwSmp4',
    appId: '1:501979216694:android:470057ebc4f8d359d41197',
    messagingSenderId: '501979216694',
    projectId: 'scholrx-beed0',
    storageBucket: 'scholrx-beed0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGQxSKFZzCl0neW46cUagvz17G36iVRpI',
    appId: '1:501979216694:ios:2e855b3d23af5300d41197',
    messagingSenderId: '501979216694',
    projectId: 'scholrx-beed0',
    storageBucket: 'scholrx-beed0.firebasestorage.app',
    iosBundleId: 'com.example.schlorx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGQxSKFZzCl0neW46cUagvz17G36iVRpI',
    appId: '1:501979216694:ios:2e855b3d23af5300d41197',
    messagingSenderId: '501979216694',
    projectId: 'scholrx-beed0',
    storageBucket: 'scholrx-beed0.firebasestorage.app',
    iosBundleId: 'com.example.schlorx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC12Q8gbHWRgxncs-6pD24aQvW0a36Jro',
    appId: '1:501979216694:web:b5afeeddda9aa889d41197',
    messagingSenderId: '501979216694',
    projectId: 'scholrx-beed0',
    authDomain: 'scholrx-beed0.firebaseapp.com',
    storageBucket: 'scholrx-beed0.firebasestorage.app',
    measurementId: 'G-Z1352MH0F7',
  );
}
